
services:
  reverse-proxy:
    image: traefik:3.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  # Ajout pour le challenge TLS
      - "8080:8080" # Tableau de bord de Traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443 # Entrypoint HTTPS activé
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Permet à Traefik d'accéder aux informations des conteneurs Docker
      - ./letsencrypt:/letsencrypt
    networks:
    - traefik-network
    

  wordpress:
    image: wordpress:6.7
    container_name: wordpress
    restart: unless-stopped

    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    ports:
      - "81:80"

    volumes:
      - wordpress_data:/var/www/html

    depends_on:
      db:
        condition: service_healthy

    labels:
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.localhost`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress.middlewares=redirect-to-https"
    networks:
      - wp-network
      - traefik-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_RT_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - wp-network
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 30s

  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped

    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - "82:80"

    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_RT_PASSWORD}

    depends_on:    
      db:
        condition: service_healthy

    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin.middlewares=redirect-to-https"
    networks:
      - wp-network
      - traefik-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: unless-stopped

    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      #- sonarqube_extensions:/opt/sonarqube/extensions --> pas assez
      #- sonarqube_logs:/opt/sonarqube/logs

    depends_on:
      sonar_db:
        condition: service_healthy

    labels:
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.localhost`)"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarqube.middlewares=redirect-to-https"
      
    networks:
      - sonar_network
      - traefik-network



  sonar_db:
    image: postgres:alpine
    container_name: sonar_db
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - sonar_network
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar","-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 5 
      start_period: 30s
    

volumes:
  postgres_data:
  wordpress_data:
  sonarqube_data:
  db_data:

networks:
  
  traefik-network:
    driver: bridge
  sonar_network:
    driver: bridge
  wp-network:
    driver: bridge